### ISSUE TITLE
output to sumo fails without source_host

### ISSUE THREAD

**Issue by akilada** [SumoLogic/logstash-output-sumologic#16]
In the documentation it says "source_host" in not mandatory. However, in version "1.1.2"  output to sumo if you do not specify "source_host".

Documentation needs to be updated.
```   
      output {
      if [@metadata][to_sumologic] == "1" {
        sumologic {
          url => "<URL>"
          format => "%{@timestamp} %{@json}"
          source_category => "<CATEGORY>"
          source_host => "<HOSTNAME>"
        }
      }
    }

**Comment by bin3377** [comment]
Hi @akilada , in my testing, if not put `source_host`, the value will be set as the result of `hostname` command. What's the error or output when you not specify `source_host` ? 

BTW, it's probably has problem if running on Windows since there is no `hostname` command by default. If that's the case, you may create a `hostname.cmd` with single line `@echo %COMPUTERNAME%` in it and place somewhere in the PATH for a workaround
